/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "eu-west-1",
  "aws_cognito_identity_pool_id": "eu-west-1:44910eff-bd48-40a2-8239-f6916e441f67",
  "aws_cognito_region": "eu-west-1",
  "aws_user_pools_id": "eu-west-1_O50m9tSOt",
  "aws_user_pools_web_client_id": "baujiil0shng2k5gbpqboh9a5",
  "oauth": {},
  "aws_user_files_s3_bucket": "homey-community-store-amplify135638-staging",
  "aws_user_files_s3_bucket_region": "eu-west-1",
  API: {
    endpoints: [
      {
        name: 'hcsapi',
        endpoint: 'https://wwol1djk7k.execute-api.eu-west-1.amazonaws.com'
      }
    ]
  }
};


export default awsmobile;
